bridge_name: ovs-br0
PXENic: nic3
BondNic1: nic1
BondNic2: nic2
InternalNetworkVlanID: 3023
ExternalNetworkVlanID: 3024
TenantNetworkVlanID: 3025
StorageNetworkVlanID: 3021
StorageMgmtNetworkVlanID: 3022
ExternalNetworkGateway: 10.0.124.1
dns_server: 10.0.120.21
network_template: bond_with_vlan_openstack
