# This role default setups node with two networks bridged by
# ovs bridge, and bonded with linux bond with mode 4. You can
# overwrite define your template to customize your own network.

- name: Install os-net-config
  package:
    name: os-net-config
    state: present
  become: true

- name: Install openvswitch
  package:
    name: openvswitch
    state: present
  become: true

- name: Start openvswitch
  service:
    name: openvswitch
    state: started
  become: true

- name: create os-net-config configuration directory
  file:
    path: /etc/os-net-config
    state: directory
    mode: 0755

- name: create os-net-config config.yml
  template:
    src: "{{ network_template }}.yml.j2"
    dest: /etc/os-net-config/config.yml
    mode: 0644

- name: execute os-net-config
  shell: os-net-config -vc /etc/os-net-config/config.yml --cleanup
  become: true
