network_template: bond_with_vlan

# Options in bond_with_vlan template

# should set in config.yml
OVSBridgeName:
NIC1:
NIC2:
StorageNetworkVlanID:
StorageNetworkGateway:
StorageMgmtNetworkVlanID:

# should set in hostvars, for example:
# [nodes]
# node1 StorageIpSubnet=192.168.0.31/24 StorageMgmtIpSubnet=192.168.1.31/24
# node2 StorageIpSubnet=192.168.0.32/24 StorageMgmtIpSubnet=192.168.1.32/24
StorageIpSubnet:
StorageMgmtIpSubnet:

# should be default
MTU: 1500
LinuxBondName: bond0
LinuxBondOptions: "mode=802.3ad lacp_rate=1 updelay=1000 miimon=100"
