network_template: bond_with_vlan_openstack

# Options in bond_with_vlan template

dns_server:

# should set in config.yml
bridge_type: ovs_bridge
bridge_name:

# If you wrongly specify the nic mapping, resulting network unreachable,
# you can login the machine through ipmi console, configure the pxe nic
# manually, such as: ip a add 10.0.120.31/24 dev enp4s0f0,  and re-run
# the ansible playbook, it will cleanup the old configuration, and reconfigure
# the network.
PXENic:
BondNic1:
BondNic2:

# As there is only one default route in one host route table,
# so these two gateway can not be specified at the same time.
PXENetworkGateway:
ExternalNetworkGateway:
StorageNetworkGateway:

InternalNetworkVlanID:
ExternalNetworkVlanID:
TenantNetworkVlanID:
StorageNetworkVlanID:
StorageMgmtNetworkVlanID:

# should set in hostvars, for example:
# [nodes]
# node1 PXENetworkSubnet=192.168.0.31/24 StorageIpSubnet=192.168.1.31/24 StorageMgmtIpSubnet=192.168.2.31/24
# node2 PXENetworkSubnet=192.168.0.32/24 StorageIpSubnet=192.168.1.32/24 StorageMgmtIpSubnet=192.168.2.32/24
# node3 PXENetworkSubnet=192.168.0.33/24 StorageIpSubnet=192.168.1.33/24 StorageMgmtIpSubnet=192.168.2.33/24
PXENetworkSubnet:
InternalIpSubnet:
ExternalIpSubnet:
TenantIpSubnet:
StorageIpSubnet:
StorageMgmtIpSubnet:

# should be default
MTU: 1500
LinuxBondName: bond0
LinuxBondOptions: "mode=802.3ad lacp_rate=1 updelay=1000 miimon=100"
