---
- name: Configuration python inspection
  block:
    - name: move collect python
      template:
        src: collect-{{env_version}}.py.j2
        dest: /tmp/collect-{{env_version}}.py
    - name: move env keystone
      template:
        src: admin-openrc.j2
        dest: /tmp/admin-openrc
    - name: running inspection python script
      shell :  source /tmp/admin-openrc && python /tmp/collect-{{env_version}}.py
    - name: mv collect information
      fetch:
        src: /tmp/{{cloudname}}
        dest: /tmp/
    - name: remove collect.py
      file:
        state: absent
        path: '/tmp/collect-{{env_version}}.py'
    - name: remove admin-openrc
      file:
        state: absent
        path: '/tmp/admin-openrc'
  become: true
  become_user: "{{running_user}}"
