---
- name: Configuration python inspection
  block:
    - name: move collect python
      template:
        src: collect-uos2.py.j2
        dest: /opt/collect.py
    - name: move env keystone
      template:
        src: admin-openrc.j2
        dest: /opt/admin-openrc
    - name: running inspection python script
      shell :  source /opt/admin-openrc && python /opt/collect.py
      register: result
    - name: remove collect.py
      file:
        state: absent
        path: '/opt/collect.py'
  become: true
  become_user: root

- name: Configuration python generate word
  block:
    - name: move docx module
      copy:
        src: "{{ docx_module }}"
        dest: /tmp/{{docx_module}}.docx
    - name: move collect-word python
      template:
        src: generate-word.py.j2
        dest: /tmp/generate-word-{{cloudname}}.py
    - name: running collect-word.py
      shell: python /tmp/generate-word-{{cloudname}}.py
      register: time
    - name: move send email python
      template:
        src: send_email_stmp.py.j2
        dest: /tmp/send_email_stmp-{{cloudname}}.py
    - name: running send email
      shell: python /tmp/send_email_stmp-{{cloudname}}.py
    - name: remove generate-word-{{cloudname}}.py
      file:
        state: absent
        path: /tmp/generate-word-{{cloudname}}.py
    - name: remove /tmp/reporter-{{cloudname}}.py
      file:
        state: absent
        path: /tmp/reporter-{{cloudname}}.py
    - name: remove /tmp/send_email_stmp-{{cloudname}}.py
      file:
        state: absent
        path: /tmp/send_email_stmp-{{cloudname}}.py
  delegate_to: "localhost"
