---
- name: Make a report dir
  block:
    - name: mkdir report
      file:
        path: "/tmp/report"
        state: directory
  delegate_to: "localhost"
- name: Configuration python inspection
  block:
    - name: move collect python
      template:
        src: collect-{{env_version}}.py.j2
        dest: /tmp/collect-{{env_version}}.py
    - name: move env keystone
      template:
        src: admin-openrc.j2
        dest: /tmp/admin-openrc
    - name: running inspection python script
      shell :  source /tmp/admin-openrc && python /tmp/collect-{{env_version}}.py
    - name: mv collect information
      fetch:
        src: /tmp/{{cloudname}}
        dest: /tmp/report/
    - name: remove collect.py
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /tmp/collect-{{env_version}}.py
        - /tmp/admin-openrc
  become: true
  become_user: "{{running_user}}"
