jira:
  server: "https://service.ustack.com"
  auth:
    username: "username"
    password: "password"
  
smtp:
  host: "smtp.exmail.qq.com"
  port: 465
  use_tls: false
  use_ssl: true
  username: "service@unitedstack.com"
  password: "password"
  from_email: "service@unitedstack.com"

recipients:
  daily:
    - guangyu@unitedstack.com
  weekly:
    - guangyu@unitedstack.com
